Update: README.md
2bs2bs/syukan_meter pull request #12
Opened 2023-12-08 08:27 UTC by 2bs2bs

新たにREADME用にブランチを作成しました。

2023-12-08 10:25 UTC, tarakish requested changes
確認しました。以下コメントです！

---
■このサービスへの思い・作りたい理由
少しエピソードが弱い印象を受けました。
このサービスを使ったことでユーザーにどういった価値を提供したいかといった目線でもう少し深掘れると良いかと思いました。

■ターゲット
少しターゲット層がざっくりしている印象を受けました。
学習習慣を身に着けたいユーザーであっても、資格試験などの比較的短期間のユーザーもいればエンジニア転職のような長期間を目標にするユーザーもいるかと思うのでもう少し絞り込めると、よりユーザーに価値の訴求がしやすくなるかと思います。

■差別化、売りのポイント
上記のターゲット、サービスへの思いを修正後、差別化ポイントを再考してみてください。

2023-12-10 02:52 UTC, 2bs2bs commented
お待たせしました！再考しましたのでレビューお願い致します！

2023-12-10 03:54 UTC, O-H-K-N commented
ありがとうございます。
私からもコメントです。

- ユーザー層で「誰かと一緒に学習をしたい方。」とありますが、他者と一緒に何かができるといった機能などはあるのでしょうか？
- 機能候補が少ないのでもう少し書きましょう！他にもあるはずなので、具体的に書いてみましょう。

2023-12-10 04:07 UTC, 2bs2bs commented
レビューありがとうございます！再考してコミットします！

2023-12-10 04:21 UTC, 2bs2bs commented
レビューお願い致します！

2023-12-10 05:18 UTC, O-H-K-N commented
LGTMです。
次に進んでください。

2023-12-10 05:20 UTC, merged

2023-12-10 05:21 UTC, 2bs2bs commented
ありがとうございます！頑張ります！